BEGIN TRANSACTION;
CREATE TABLE "GanttResources" ("ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL  ,"Name" NVARCHAR(50)  NOT NULL  ,"Color" CHAR(10)  NULL DEFAULT NULL );
INSERT INTO `GanttResources` VALUES (1,'Thomas Hardy','#f44336   ');
INSERT INTO `GanttResources` VALUES (2,'Elizabeth Lincoln','#880e4f   ');
INSERT INTO `GanttResources` VALUES (3,'Christina Berglund','#ff4081   ');
INSERT INTO `GanttResources` VALUES (4,'Martín Sommer','#9c27b0   ');
INSERT INTO `GanttResources` VALUES (5,'Patricio Simpson','#3d5afe   ');
INSERT INTO `GanttResources` VALUES (6,'Francisco Chang','#2196f3   ');
INSERT INTO `GanttResources` VALUES (7,'Yang Wang','#ff7043   ');
INSERT INTO `GanttResources` VALUES (8,'Pedro Afonso','#ff9800   ');
INSERT INTO `GanttResources` VALUES (9,'Elizabeth Brown','#6d4c41   ');
INSERT INTO `GanttResources` VALUES (10,'Sven Ottlieb','#64dd17   ');
INSERT INTO `GanttResources` VALUES (11,'Roland Mendel','#00bfa5   ');
INSERT INTO `GanttResources` VALUES (12,'Marie Bertrand','#01579b   ');
INSERT INTO `GanttResources` VALUES (13,'Catherine Dewey','#d500f9   ');
INSERT INTO `GanttResources` VALUES (14,'Marketing Team','#e91e63   ');
INSERT INTO `GanttResources` VALUES (15,'Design Team','#3f51b5   ');
INSERT INTO `GanttResources` VALUES (16,'Engineering Team','#607d8b   ');
INSERT INTO `GanttResources` VALUES (17,'QA Team','#43a047   ');
INSERT INTO `GanttResources` VALUES (18,'Documentation Team','#26c6da   ');
COMMIT;