#!/bin/zsh

for file in `ssh $1 "find /var/lib/jenkins/jobs/ -maxdepth 1 -mindepth 1"`
    scp $1:$file/config.xml cookbooks/jenkins-jobs/files/default/jobs/${file##*/}.xml

for file in `ssh $1 "find /var/lib/jenkins/*.xml -maxdepth 0 -mindepth 0"`	      
    scp $1:$file cookbooks/jenkins-jobs/files/default/${file##*/}
